# Основные цвета
background            #0e1514
foreground            #dde4e2
cursor                #80d5cf
selection_background  #324b49
selection_foreground  #cce8e5

# Цвета 0-7 (Normal)
color0  #0e1514
color1  #ffb4ab
color2  #80d5cf
color3  #b0ccc9
color4  #b0c9e7
color5  #00504d
color6  #324b49
color7  #bec9c7

# Цвета 8-15 (Bright)
color8  #889391
color9  #93000a
color10 #80d5cf
color11 #b0ccc9
color12 #b0c9e7
color13 #006a66
color14 #314962
color15 #dde4e2
